FROM node:18.15-slim

WORKDIR /usr/src/app

# COPY package*.json ./
# COPY .env ./

COPY . .

RUN npm install

RUN npm run lint

# RUN npm run test
# Expose port 8080
EXPOSE 8080

CMD ["npm", "run", "start"]
